### ISSUE TITLE
Looks pretty good...

### ISSUE THREAD

**Issue by paulgureghian** [Kir-Antipov/GitHub-Defreshed#1]
the one thing that was not restored is the 'followers' 'following' 'stars' links which were on the top in profile. other than that it looks like the old ui. of course I don't remember every single detail of the old ui, I would have to look at old screenshots, but it looks pretty close to it. looks better than the new ui that's for sure.

**Comment by paulgureghian** [comment]
I just this extension does not crash my browser. if you update the repo will my extension automatically update itself ?

**Comment by Kir-Antipov** [comment]
> the one thing that was not restored is the 'followers' 'following' 'stars' links which were on the top in **profile**

At the moment, this repo focuses only on reviving the original appearance of **repositories**, as they have suffered the most.
As for me, all the other changes didn't become so terrible for GitHub :)

> but it looks pretty close to it. looks better than the new ui that's for sure

Thanks a lot xD

> I just this extension does not crash my browser

Didn't get what you mean, tbh...

> if you update the repo will my extension automatically update itself ?

Absolutely

**Comment by Kir-Antipov** [comment]
Well, I'll close this issue, cause it's not really an issue :)

If you'll find something is missing from/wrong with repo page, feel free to open new issue!
