### ISSUE TITLE
No CI status displayed in commit message on repository front page

### ISSUE THREAD

**Issue by MrNaif2018** [Kir-Antipov/GitHub-Defreshed#13]
Hello! First of all, thank you very much for your extension to bring old good github back!
When viewing my repository front page, I don't see CI build mark (green checkmark or red depending on build status), but when viewing full commits list I can see that. 
Version 1.6.0
Seems to be related to latest commit message "improvements".
Screenshots:
![изображение](https://user-images.githubusercontent.com/39452697/88420282-4ebb5880-cdef-11ea-804e-43de727d2759.png)
![изображение](https://user-images.githubusercontent.com/39452697/88420300-54b13980-cdef-11ea-8b94-36894c3ca198.png)

**Comment by Kir-Antipov** [comment]
Hi there!

> First of all, thank you very much for your extension to bring old good github back!

Thanks a lot, I'm very glad that my script was useful to you!

> I don't see CI build mark

Yeah, that's true. Just noticed that Microsoft has moved the build status to the different location (I'd even say they moved it to *ebenya* from its usual location).

Very glad that you brought this to my attention! 

Is this bug critical for you? I'm currently preparing a big update, which I'll release in a couple of days, so I could add fix for that there. If you need this functionality right now, I'll release the fix tomorrow :)

**Comment by Kir-Antipov** [comment]
Done. Waits to be included in new release, so let me know if it can wait a couple of days or if you need it as soon as possible

![img](https://user-images.githubusercontent.com/40232067/88437695-abc70680-ce0f-11ea-9292-6ceb2f1d39a0.png)

**Comment by MrNaif2018** [comment]
Of course it can wait a couple of days! Thank you for the quick fix! Really appreciate it!

**Comment by Kir-Antipov** [comment]
@MrNaif2018, it took a little bit longer than I expected, but update is finally ready! It also fixes your problem, so don't forget to upgrade your script version to `v2.0.0`!

**Comment by MrNaif2018** [comment]
Thank you! It works perfectly! Will help in finding bugs in the future too! :D
