### ISSUE TITLE
Missing project website on about

### ISSUE THREAD

**Issue by An-dz** [Kir-Antipov/GitHub-Defreshed#14]
The project website is not being added in the about section. Now it's on a new element so you missed it.

Example page:
https://github.com/Nuitka/Nuitka

Old layout:
https://web.archive.org/web/20200611130431/https://github.com/Nuitka/Nuitka

**Comment by Kir-Antipov** [comment]
Ahah, surprisingly, I managed to forget about the website section from the very first release, although I was sure that I did it after all xD

Thanks so much for pointing out this problem, and it's also great that you provided the Web Archive example, really appreciate it!

**Comment by Kir-Antipov** [comment]
Done :)
This fix will appear in the upcoming update

**Comment by Kir-Antipov** [comment]
@An-dz, huh, the update's finally ready! It also includes fix for this issue. 

Don't forget to upgrade your script version to `v2.0.0`, there're a lot of cool stuff :)
