### ISSUE TITLE
Different UI when opening master branch and a different branch (with branch diff message)

### ISSUE THREAD

**Issue by MrNaif2018** [Kir-Antipov/GitHub-Defreshed#15]
Hello! Thank you for quick version 2, and that's me once again telling about bugs (:
This bug appears when opening a branch different from master, the layout changes to something mixed between old and new style (actually it looks not bad :D, but commits link and some other stuff is hidden).
I can't seem to reproduce this on third-party repos, I can only reproduce it only on my repos, so looks like it is caused by "Recent pushes on some branch" message though I don't see it.
[Link to the branch if it shows for you too](https://github.com/MrNaif2018/bitcart/tree/feature/tor)
Version 2.0
Screenshots:
Default branch:
![изображение](https://user-images.githubusercontent.com/39452697/88698227-7885bf80-d10e-11ea-943a-c10d95575de8.png)
PR branch:
![изображение](https://user-images.githubusercontent.com/39452697/88698295-8afff900-d10e-11ea-9613-167a7e107fcb.png)

**Comment by Kir-Antipov** [comment]
Uh oh
Problem's caused by your branch name, not by "Recent pushes on some branch"

> https://github.com/MrNaif2018/bitcart/tree/feature/tor

It's impossible to say where am I by just looking at this link: it can be "tor" folder of "feature"-branch (the most common case) or it can be the root of the "feature/tor"-branch (your case).

At the moment, the script is configured for the most common case, so that no fixes for the repository root are applied to this page.

But don't worry, as always I have an idea how to fix it by few more heuristics :)

**Comment by MrNaif2018** [comment]
Oh, I thought that this branch name might cause problems! But catching rare cases is good too (:
Thank you!

**Comment by Kir-Antipov** [comment]
> But catching rare cases is good too (:

Jokes on you, of course they are!)
I faced this bug a long time ago, but that time edge-case handling wasn't part of the plans yet, as the script was in its early stages of development. And now when I'm pretty happy with the results, the time has come :)

Well, I can get branches from the branch-button content:
```js
let branches = [...document.querySelectorAll("#ref-list-branches > .SelectMenu-list > a > span:not(.Label)")].map(x => x.innerText.trim());
```

I hope that at least no one uses the "/" character in tags xD

**Comment by Kir-Antipov** [comment]
Voila!
Even `dependabot/pip/bitcart-async-0.9.0` works fine now :)

![fix](https://user-images.githubusercontent.com/40232067/88727787-f19a0c80-d138-11ea-964b-f6afb4aead27.png)
