### ISSUE TITLE
Releases count missing on some repos

### ISSUE THREAD

**Issue by MrNaif2018** [Kir-Antipov/GitHub-Defreshed#16]
Hello! One more rare bug (: 
It looks like when opening a repository which has either only tags, or only pre-releases, release count stays 0.
I saw [your comment](https://github.com/Kir-Antipov/GitHub-Defreshed/issues/10#issuecomment-658085198) about that, but actually original github UI did display that.
Sample repositories:
https://github.com/nuxt-community/eslint-module (tags only)
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded from #10 
Version 2.0
Here is web archive [link](http://web.archive.org/web/20200131010925/https://github.com/Cxbx-Reloaded/Cxbx-Reloaded) from January 2020
Screenshots:
![изображение](https://user-images.githubusercontent.com/39452697/88704000-2183e880-d116-11ea-9aee-ed06376a2dd9.png)
![изображение](https://user-images.githubusercontent.com/39452697/88704018-2a74ba00-d116-11ea-87c4-ae1a64b36a5e.png)
![снимок](https://user-images.githubusercontent.com/39452697/88704294-8c352400-d116-11ea-859f-3089a78cfc21.png)
![изображение](https://user-images.githubusercontent.com/39452697/88704358-a2db7b00-d116-11ea-9c86-6ac9331423a9.png)
![изображение](https://user-images.githubusercontent.com/39452697/88704438-be468600-d116-11ea-97ba-04544286cc01.png)

**Comment by Kir-Antipov** [comment]
> One more rare bug (:

Well, it's not so rare if there're 2 issues about it already)

> ...but actually original github UI did display that

Hm. It changes things completely. Ok, will show tags count if there're not any actual releases

**Comment by Kir-Antipov** [comment]
Done:

![fix](https://user-images.githubusercontent.com/40232067/88730361-90753780-d13e-11ea-8d9b-8d36c601ffcf.png)

Also I made this behavior optional, so you can disable it if you want:

![settings](https://user-images.githubusercontent.com/40232067/88730479-c87c7a80-d13e-11ea-9954-ce6c59f3081f.png)

**Comment by MrNaif2018** [comment]
Amazing! Thank you again! Now it is perfect (:
