### ISSUE TITLE
they do something agian?

### ISSUE THREAD

**Issue by medievil1** [Kir-Antipov/GitHub-Defreshed#17]
![image](https://user-images.githubusercontent.com/38597905/89078426-67c58b80-d352-11ea-89d1-bff41fc8d7a8.png)

**Comment by Kir-Antipov** [comment]
@medievil1, please, check the actual script version before opening new issue :)
I've fixed it 2 days ago: https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v2.1.0

**Comment by medievil1** [comment]
sorry autoupdate on the script isn't working apparently

**Comment by Kir-Antipov** [comment]
@medievil1, that's true. Update-checks sometimes run on a really weird schedule. Perhaps I'll add an optional update reminder directly to the script

**Comment by medievil1** [comment]
yea mine was still on 1.6 so I dunno how many updates it skipped over

**Comment by Kir-Antipov** [comment]
@medievil1, hm. Did you use simplified version?

**Comment by medievil1** [comment]
not sure what you mean, just regular greasemonky on firefox

**Comment by Kir-Antipov** [comment]
There were 2 script versions before 2.0.0: original and simplified (without CSS). After 2.0.0 came out, simplified version had been deprecated since script has its own settings now and there's no need in different versions with different functionality. 
Since simplified version was deprecated, it can't be updated automatically. That's the point I'm talking about

**Comment by medievil1** [comment]
ahhh.. no idea... should be good now since it is current , script has update url and all that in it

**Comment by medievil1** [comment]
this was the link I installed from initially though (on the front page)
https://raw.githubusercontent.com/Kir-Antipov/GitHub-Defreshed/master/build/github-defreshed.user.js

**Comment by Kir-Antipov** [comment]
Well, than it's Greasemonkey's fault and I definitely must implement an update reminder :)
