### ISSUE TITLE
Broken link for contributors on forks

### ISSUE THREAD

**Issue by An-dz** [Kir-Antipov/GitHub-Defreshed#19]
On forked repositories the contributors link is broken, the user name is duplicated on the URL. I guess the reason is because GitHub decided to not show contributors on forks so the script fails to obtain the number of contributors and fallback to showing a single contributor.

Here's a repo that is a fork:
https://github.com/rust-lang/rust-enhanced

Seeing on archive that's something the redesign changed as it used to show up:
https://web.archive.org/web/20200530174346/https://github.com/rust-lang/rust-enhanced

**Comment by Kir-Antipov** [comment]
> I guess the reason is because GitHub decided to not show contributors on forks so the script fails to obtain the number of contributors and fallback to showing a single contributor

Absolutely true! Will fix it soon

By the way, thank you so much for all your issues, they really help improve the script! :)

**Comment by Kir-Antipov** [comment]
Okay, maybe this will take a couple of days. I want to refactor some things and restructure the repository a little bit first

**Comment by Kir-Antipov** [comment]
I'm sorry it took me so long. I had to deal with a couple of deadlines :)

This fix will be available in [v2.1.5](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v2.1.5)

**Comment by An-dz** [comment]
No problem, it's not like I would die without that :D
