### ISSUE TITLE
Top bar fails to render on refresh

### ISSUE THREAD

**Issue by An-dz** [Kir-Antipov/GitHub-Defreshed#2]
When loading the code tab from a link or by doing a refresh the script fails to execute.

The log is basically that it could not find the DOM.

```
Fixer exception:  TypeError: Cannot read property 'querySelector' of null
    at x.isApplieble._createCommitsSummaryElement (github-defreshed.user.js:15)
    at x.isApplieble.apply (github-defreshed.user.js:15)
    at k (github-defreshed.user.js:15)
```

**Comment by Kir-Antipov** [comment]
@An-dz, can not reproduce this. Can you provide a link to some problematic repos, please?

**Comment by Kir-Antipov** [comment]
Also, it would be nice if you'll mention your browser and userscript engine, just in case :)

**Comment by An-dz** [comment]
Ok, I've found the problem, I somehow changed the execution time of the script so it was firing too early. It's all good now.

**Comment by Kir-Antipov** [comment]
@An-dz, oh, ok xD
Yeah, that kinda make sense, cause currently I need fully loaded DOM at startup. Will change it in nearest future
