### ISSUE TITLE
Add the version number to the summary bar

### ISSUE THREAD

**Issue by Kir-Antipov** [Kir-Antipov/GitHub-Defreshed#23]
I always wanted to see the version number in the summary bar and that's something that was added somewhat hidden in the new crappy layout.

I think adding a popup that when hovering the releases button shows the latest version number/name and when it was released and then an option to change which shows in the popup and which in the text would be nice. This way both options can see the latest version number and the number of releases.

_Originally posted by @An-dz in https://github.com/Kir-Antipov/GitHub-Defreshed/issues/21#issuecomment-683946938_

**Comment by Kir-Antipov** [comment]
@An-dz, what do you think about using built-in GitHub tooltips for these purposes?

![Popup](https://user-images.githubusercontent.com/40232067/91853317-ae1c4c00-ec6a-11ea-963b-d6d20ea6da59.png)

**Comment by An-dz** [comment]
That's what I was thinking in the first place :wink:

**Comment by Kir-Antipov** [comment]
@An-dz, ok, I'm on it :)

**Comment by Kir-Antipov** [comment]
**stale**, go away

**Comment by An-dz** [comment]
Really cool, it looks great. :+1:

**Comment by Kir-Antipov** [comment]
@An-dz, thanks a lot! I apologize for hardcoding the format of the text in the popup, but I literally have no time right now, so... :)

**Comment by An-dz** [comment]
No problem at all. Now the frontpage has all the info needed.
