### ISSUE TITLE
some pages still display incorrectly

### ISSUE THREAD

**Issue by medievil1** [Kir-Antipov/GitHub-Defreshed#38]
## Description

page only partially reverts to old
## Other information

https://github.com/NZJenkins/Cxbx-Reloaded/tree/hlsl/metal-arms
can't do web archive since it is a newer branch
it should however look like another branch from same repo https://github.com/NZJenkins/Cxbx-Reloaded/tree/ivb-float4
Firefox 88.0.1
-windows 10
refreshed version 4.3.0 - tampermonkey, triggered update and it says no update available

**Comment by Kir-Antipov** [comment]
Hm, I think #15 strikes back

**Comment by medievil1** [comment]
ahhh yea I DO see that / now, it's a branch in a branch..... interesting... if it can't be fixed, oh well... that should be a rare case anyway

**Comment by Kir-Antipov** [comment]
Yep, this is such a rare problem that I haven't know that my fix of the #15 doesn't work properly until this very moment :D

I'll take a closer look at the issue tomorrow
