### ISSUE TITLE
Can't open repository page

### ISSUE THREAD

**Issue by An-dz** [Kir-Antipov/GitHub-Defreshed#39]
## Description

The repository page does not want to open with 4.3.1, had to revert to 4.3.0. Error log is below.

Everything else works.

## Log

```
Uncaught (in promise) TypeError: Cannot read property 'whenDefined' of null
    at Object.<anonymous> (github-defreshed.user.js:16)
    at Generator.next (<anonymous>)
    at a (github-defreshed.user.js:16)
```

## Other information

- **Link to page with the issue**: https://github.com/Kir-Antipov/GitHub-Defreshed
- **Browser**: Vivaldi w/ Chromium 91.0.4472.66 & Woolyss Ungoogled Chromium 90.0.4430.212
- **Operating System**: Windows 10 x64 20H2
- **GitHub-Defreshed version**: 4.3.1 user-script version

**Comment by Kir-Antipov** [comment]
Well, it seems that [whenDefined](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined) isn't supported by your browser. Wait a moment, please, will fix it in a moment

**Comment by Kir-Antipov** [comment]
I hope [v4.3.2](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v4.3.2) is okay :)

**Comment by Kir-Antipov** [comment]
Note: in fact, custom elements are supported by the browser, but access to this functionality from content scripts is limited (as far as I can say by this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=390807))

**Comment by An-dz** [comment]
Still broken. But now there's no error on console, the loading just keeps spinning forever.

Checking the HTML it's normal crappy GitHub.

**Comment by Kir-Antipov** [comment]
Hm. It's really strange. I'm very sorry for the inconvenience, tomorrow I'll try to find a solution to this problem

**Comment by Kir-Antipov** [comment]
Hi! Didn't issue magically resolve itself while I was asleep? :D

Cannot reproduce the issue with Ungoogled Chromium 90.0.4430.212
![image](https://user-images.githubusercontent.com/40232067/119472397-e280ec80-bd52-11eb-8779-f3f63636bc8f.png)

**Comment by Kir-Antipov** [comment]
If the problem persists, could you run this snippet on the repository page while it refuses to load, please?

```js
const refSelector = document.querySelector("#branch-select-menu ref-selector");
console.log(refSelector.constructor);
await refSelector.index.fetchData();
console.log(refSelector.index.currentSearchResult);
```

Expected output: 
![image](https://user-images.githubusercontent.com/40232067/119481130-0ba57b00-bd5b-11eb-99b0-3b0059db62c0.png)

**Comment by An-dz** [comment]
The output is the same as your image and putting `RefSelectorElement` on the content script says it's not available, as I expected since content scripts can't access the page variables as it runs on a separate layer.

The same problem is happening on Firefox 78.

**Comment by Kir-Antipov** [comment]
> Content scripts can access and modify the page's DOM, just like normal page scripts can. They can also see any changes that were made to the DOM by page scripts.
> However, content scripts get a "clean" view of the DOM. This means:
> - Content scripts cannot see JavaScript variables defined by page scripts.
> - If a page script redefines a built-in DOM property, the content script sees the original version of the property, not the redefined version.

Oh. Now I see. But I can't understand 2 things:
1) Why is this even a thing? "Clean view of the DOM". Benefits of this are highly questionable
2) Why it doesn't work for me (-> GitHub-Defreshed doesn't fail)? :D

**Comment by An-dz** [comment]
> Why is this even a thing? "Clean view of the DOM". Benefits of this are highly questionable

Yes, not "write" to it seems reasonable so you don't need to worry about your variables breaking the page, but reading is pretty dumb.

> Why it doesn't work for me (-> GitHub-Defreshed doesn't fail)? :D

At first I thought it could be you using Firefox, but it fails on mine and you have tested on Chromium.

But maybe it's how we have installed it. Are you using your XPI for Firefox? Or GreaseMonkey?

**Comment by Kir-Antipov** [comment]
> Yes, not "write" to it seems reasonable so you don't need to worry about your variables breaking the page, but reading is pretty dumb

Completely agree! *"This means that content scripts can rely on DOM properties behaving predictably, without worrying about its variables clashing with variables from the page script."* Guys, "DOM properties behave predictably" when and only when they work same way they do when I'm browsing the website I made the script for...

----

> But maybe it's how we have installed it. Are you using your XPI for Firefox? Or GreaseMonkey?

Ahaha, I forgot about GreaseMonkey :D I use TamperMonkey *(yep, I know it's closed-source and so on, but I'm just used to it)* and it seems it doesn't use Content Script API :D

**Comment by Kir-Antipov** [comment]
Well, I hope I've fixed the issue *(+1 api call due to Content Script API restrictions -_-)*. Could you please check if this fix works for you, so I won't release broken version again? :D

You can grab build artifacts [here](https://github.com/Kir-Antipov/GitHub-Defreshed/actions/runs/875891191)

**Comment by An-dz** [comment]
> Ahaha, I forgot about GreaseMonkey :D I use TamperMonkey _(yep, I know it's closed-source and so on, but I'm just used to it)_ and it seems it doesn't use Content Script API :D

I don't use GreaseMonkey either, I used to use [ViolentMonkey](https://github.com/violentmonkey/violentmonkey), but now I just create a pseudo-extension with a manifest and load from disk. For Firefox I use your XPI.

> Well, I hope I've fixed the issue _(+1 api call due to Content Script API restrictions -_-)_. Could you please check if this fix works for you, so I won't release broken version again? :D

It works now. 👍

**Comment by Kir-Antipov** [comment]
> I don't use GreaseMonkey either, I used to use ViolentMonkey, but now I just create a pseudo-extension with a manifest and load from disk. For Firefox I use your XPI

Isn't it a little bit tedious to do all of these manually? Why did you stop using ViolentMonkey?

> It works now. 👍

Finally, haha :) I'll make few more changes (aka fixes, e.g., busy status is broken again) and then will release new version

Thank you so much for helping out with this one! I'm always too lazy to check that everything works outside of my usage scope (Firefox + userscript), so Chrome/Web Extension bugs are unnoticeable for me :D

**Comment by Kir-Antipov** [comment]
[v4.3.3](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v4.3.3) (which fixes the issue) was published :)

**Comment by An-dz** [comment]
> Isn't it a little bit tedious to do all of these manually?

I just need to create the manifest once and then I just download the `.user.js` over the old one whenever you update it. GitHub alerts me when a release is made.

> Why did you stop using ViolentMonkey?

It runs over every page even though my userscripts only run over some pages, Chromium will handle that faster and more secure for me. And the only userscript I use that I have not created is yours so I don't care about manually updating it.

**Comment by Kir-Antipov** [comment]
Oh, I see, that's reasonable :)
