### ISSUE TITLE
Enabling the script renders all Project boards unusable

### ISSUE THREAD

**Issue by SacredDuckwhale** [Kir-Antipov/GitHub-Defreshed#4]
Hello again! I've discovered that enabling your script makes it impossible for me to use Project boards feature. As soon as I disable the script in GreaseMonkey and reload, everything works as expected again.

Screenshot: https://i.imgur.com/drJ287i.png
Example project: https://github.com/SacredDuckwhale/TestProject/projects/1

Hopefully this is enough to reproduce the problem.

It looks like the content isn't visible in the main container, presumably because the div with ``class="repository-content d-flex flex-auto container-lg"`` isn't sized properly? I've only taken a brief glance at the HTML, though.

**Comment by Kir-Antipov** [comment]
You're totally a day saver, thanks a lot for your initiative! :)

Hm. I can barely remember how it was supposed to look like before this update... This page seems to had an enlarged container all the time, am I right? In this case, it will be enough just to turn off some of the fixers for the project page.

**Comment by SacredDuckwhale** [comment]
This is how it looks with the new UI: https://i.imgur.com/QLDDoUL.png

The layout itself hasn't really changed, I think, they mainly just made everything round and ugly inside the containers themselves.

**Comment by Kir-Antipov** [comment]
Published a new release v1.2.5, should fix the problem :)
