### ISSUE TITLE
Can't open repository page (Firefox)

### ISSUE THREAD

**Issue by leewp14** [Kir-Antipov/GitHub-Defreshed#40]
## Description
With the latest extension (in fact I'm not aware since which version), any repository page won't open, similar to #39 but with a different error log: 
`TypeError: can't access property "fetchData", e.index is undefined`

## Screenshot
![image](https://user-images.githubusercontent.com/17796518/119658675-03833380-be60-11eb-8063-5bb8b39445ce.png)

## Other information

- **Link to page with the issue**: https://github.com/Kir-Antipov/GitHub-Defreshed
- **Web Archive example**: 
- **Browser**: Firefox Developer Edition 89.0b15
- **Operating System**: Windows 10 Enterprise-N
- **GitHub-Defreshed version**:  4.3.2

**Comment by Kir-Antipov** [comment]
In fact, it is #39, and it's already fixed in the `development` branch, so don't worry :)

Will release new version in few hours

**Comment by leewp14** [comment]
Sorry for the duplicate, many thanks for the great extension!

**Comment by Kir-Antipov** [comment]
> Sorry for the duplicate

It's totally fine :)

> many thanks for the great extension!

Thank you for using it!
