### ISSUE TITLE
Remove Public/Private badge after repo name

### ISSUE THREAD

**Issue by MillironX** [Kir-Antipov/GitHub-Defreshed#45]
## Description

GitHub now adds a badge telling you if you're in a public or private repo after the repo name.

![Public repo badge](https://user-images.githubusercontent.com/25492070/132581286-8efac85d-f47d-4fff-a143-491d4bb50c6e.png)

![Private repo badge](https://user-images.githubusercontent.com/25492070/132582057-bc03ee1f-c829-4a8e-8602-453a14d23755.png)

If I recall correctly, this badge used to exist **only** for private repos (as they went against the norm of GitHub).

I suggest that we get the option of removing this badge via one of three options:

1. Remove badge for all repos
2. Remove badge for private repos (old GitHub behavior)
3. Keep badge for all repos

## Other information

- **Web Archive example**: https://web.archive.org/web/20200131233804/https://github.com/JuliaLang/julia

Why? Having the badge there is ugly (subjective), redundant with the icon _in front_ of the name, and removes the 'normalcy' status of public repos by making them look just as awkward as private repos.

I can completely remove or keep the badge using custom uBlock origin filters, but I think the old GitHub behavior is best, and should be the default option.

**Comment by Kir-Antipov** [comment]
Agree. I'm on it
