### ISSUE TITLE
Extension is broken after latest github design updates

### ISSUE THREAD

**Issue by MrNaif2018** [Kir-Antipov/GitHub-Defreshed#46]
## Description

Recently github has been messing up with the UI (it all started with a nice kitty animation), so now repository pages at least return to something like "new" design again

In dev console I see:

`Fixer exception:  TypeError: t is null`

It is probably occurring there:

`t=e.querySelector(".gutter-condensed")`

Also just noticed, contributor count seems to be wrong, or is it github-side bug?

## Screenshot

![изображение](https://user-images.githubusercontent.com/39452697/138316703-50539dfa-ede7-4a11-91aa-9fc7b9698183.png)

## Other information

- **Link to page with the issue**:  any repository [front page](https://github.com/bitcartcc/bitcart)
- **Browser**: Firefox 93.0
- **Operating System**:  Linux Mint 20.2 
- **GitHub-Defreshed version**: 4.4.0

**Comment by Kira-NT** [comment]
Is this issue still reproducible for you? This is how I see your repo at the moment:

![image](https://user-images.githubusercontent.com/40232067/138448194-6ecaa2d6-6af9-42a0-be98-285fbb8327a4.png)

**Comment by MrNaif2018** [comment]
Yeah it is. Weird. When logged out it works (tried private mode and clearing all cookies), but when I log in it breaks, and on all repository pages, not only those I own. What could that be? Some fixer settings for profiles?

Checking html I indeed don't see `gutter-condensed` class. Not sure what are the differences between our profiles

**Comment by Kira-NT** [comment]
Weird indeed. The script is looking for `body > .application-main > div > #js-repo-pjax-container > .clearfix.new-discussion-timeline > #repo-content-pjax-container > div.gutter-condensed`:

![image](https://user-images.githubusercontent.com/40232067/138492148-b988ba72-9f46-4775-bbf9-3d0542c37583.png)

Isn't it presented for you?

**Comment by MrNaif2018** [comment]
No it isn't
![изображение](https://user-images.githubusercontent.com/39452697/138494195-ef828c6e-b137-441e-8050-e8ea6b6001e6.png)
Should I upload that html part here?

In console I also get `None of sha512 integrity match the actual hashes`. Maybe that's the case and something's wrong with my browser?

**Comment by Kira-NT** [comment]
Could you disable the extension at first, please?

**Comment by MrNaif2018** [comment]
```
<form action="/bitcartcc/bitcart/branches"
                                                            accept-charset="UTF-8" method="post"><input type="hidden"
                                                                name="authenticity_token"
                                                                value="....">
```
I wonder if the page contains any sensitive info. Do you know whether it does?

**Comment by MrNaif2018** [comment]
I've sent you an email with the html file of the issue attached (btw my invitation from older emails is still valid :smiley:)

**Comment by MillironX** [comment]
Can reproduce exactly on the following config:

- Browser: Firefox 90.0.2
- Operating System: Fedora 34
- GitHub-Defreshed version: 4.4.0
- GitHub-Defreshed install source: Greasemonkey

**Comment by medievil1** [comment]
same here, all pages partially broken
FF 93.0.0
Win 11 pro
Defreshed 4.4.0 
Tampermonkey


EDIT
Adding that I do see a feature preview options for the theme stuff and it does not change the outcome

**Comment by Kira-NT** [comment]
@MrNaif2018, thanks, deeply appreciate that! Also, don't worry, it's GitHub, not Facebook, so no really sensitive information is present on the page *("tokens" that you were concerned about are also known as "antiforgery tokens". Those are just random strings that help prevent CSRF attacks and cannot be used to steal you data)*

> (btw my invitation from older emails is still valid 😃)

Thank you! Sadly, I'm a little bit burned out at the moment, so I don't even have much energy for my own pet projects, as you can see...

**Comment by Kira-NT** [comment]
UPD: I can finally see the same HTML as you folks do. Don't know what took GitHub so long, but the fix is on its way!

**Comment by Kira-NT** [comment]
Should do the trick for the moment

**Comment by MrNaif2018** [comment]
Thanks! It works. The only thing is, I am not sure but probably comments writing field didn't have that ugly scrollbar before?
![изображение](https://user-images.githubusercontent.com/39452697/139111481-b5a4274b-ec72-4c9a-b02d-645963d0d790.png)

Also github have changed closed color to the one merged pull requests use, extremely weird decision
![изображение](https://user-images.githubusercontent.com/39452697/139111586-801f46f0-9feb-4c5a-acc9-e32e7388e8b1.png)
Oh and one more thing:
![изображение](https://user-images.githubusercontent.com/39452697/139145866-28038bda-a249-413e-809f-6aaf9f1811a9.png)
Public badge is displayed when refreshing some page other than main repository page, i.e. issue page)
Should I maybe open a separate issue for all those? @Kir-Antipov
