### ISSUE TITLE
Unable to command/ctrl click to open links in a new tab

### ISSUE THREAD

**Issue by ccampbell** [Kir-Antipov/GitHub-Defreshed#5]
Hi there, Thanks so much for all the work you put into this, it is impressive. One issue that I noticed is that when this is installed command click on links no longer opens them in a new tab. 

It seems that some links work, but some do not. I am not sure the exact behavior causing it, but probably a `preventDefault()` somewhere where it should not be `if (e.metaKey || e.ctrlKey)` is pressed 

Ah ya the problematic part looks to be:

https://github.com/Kir-Antipov/GitHub-Defreshed/blob/e5046565458d8cb757f6b013e2f049846d725e58/src/fixers/links-fixer.js#L21-L25

Anchor links also don’t seem to work correctly

**Comment by Kir-Antipov** [comment]
> Thanks so much for all the work you put into this, it is impressive

Really glad to here that :3

> command click on links no longer opens them in a new tab

Whoops, didn't noticed that cause I'm using middle mouse button for these purposes (seems like its behavior can't be overridden).

> Ah ya the problematic part looks to be [...]
> `if (e.metaKey || e.ctrlKey)` [...]

Yeah, you're absolutely right. Will fix it in a minute

> Anchor links also don’t seem to work correctly

Are you sure about that? 'Cause [v1.2.0](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v1.2.0) fixed that

**Comment by Kir-Antipov** [comment]
Fixed in [v1.3.0](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v1.3.0)

Don't forget to force your userscript engine to update the script to get fix as fast as possible :)

**Comment by ccampbell** [comment]
Thanks for the quick turnaround, just updated and it is fixed. The anchor links are still broken for me though.

To test go to your own repo page:
https://github.com/Kir-Antipov/GitHub-Defreshed

Then hover over one of the headers and click on the anchor

![image](https://user-images.githubusercontent.com/259316/86288287-aaf7d780-bbb7-11ea-9e65-4a7edb17e437.png)

It refreshes the page inline and does not link to the anchor

**Comment by Kir-Antipov** [comment]
@ccampbell, oh... Yeah... I fixed only "#" links, not "#something"... What a shame...

Moved it into new issue. Third (or even fourth) update for one day is coming xD

**Comment by Kir-Antipov** [comment]
@ccampbell, [v1.3.5](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v1.3.5) is onboard, everything should be fine now :)

**Comment by ccampbell** [comment]
Awesome, just updated and looks good 👍 will open a new issue if I run into anything else. Thanks!

**Comment by Kir-Antipov** [comment]
You're welcome! :)
