### ISSUE TITLE
Microsoft strikes back with new "design update"

### ISSUE THREAD

**Issue by Kir-Antipov** [Kir-Antipov/GitHub-Defreshed#7]
Script needs to be prepared to support a new design update ("Latest commit design updates")

![oh no](https://user-images.githubusercontent.com/40232067/86860050-c2115a80-c0cc-11ea-8978-52b53609f744.jpg)

**Comment by Kir-Antipov** [comment]
Kinda done (see [latest-commit-design-updates](https://github.com/Kir-Antipov/GitHub-Defreshed/tree/latest-commit-design-updates) branch), but I'll leave this issue open until the update comes out of the preview, 'cause something may change.

**Comment by medievil1** [comment]
new design seems to be live for me...no option to not use it and all screwed up github portal

**Comment by Kir-Antipov** [comment]
@medievil1, yep. Update is onboard now :)
