### ISSUE TITLE
Downloading releases fail

### ISSUE THREAD

**Issue by An-dz** [Kir-Antipov/GitHub-Defreshed#8]
Trying to download a release fails with a message on console saying "Failed to fetch...".

Before this message it shows some errors about CSP policy and the like.

Doesn't happen without the script.

## Reproducing

1) Open https://github.com/Kir-Antipov/GitHub-Defreshed/releases
2) Click to download a resource
3) It fails with the failed to fetch message

**Comment by Kir-Antipov** [comment]
Thanks for the report!

Yup, not a fault of the fetch, but mine :)
Will fix it in an hour

**Comment by Kir-Antipov** [comment]
Fixed in [v1.4.5](https://github.com/Kir-Antipov/GitHub-Defreshed/releases/tag/v1.4.5), don't forget to update the script! :)
